"""The database as one file.

Design notes worth knowing before reading:

* **The run row is the queue.** No broker: `runs` carries `status`, `attempts`, `heartbeat_at`
  and `deadline_at`, and the dispatcher claims with `FOR UPDATE SKIP LOCKED` (v0.6 §2). The
  status vocabulary is generated from `RunStatus`, so the contract and the CHECK constraint
  cannot drift apart.
* **`runs.event_seq` is the sequence allocator** for `run_events`. Incrementing a counter on the
  run row gives a gap-free per-run ordering that SSE can resume from with `Last-Event-ID`, which
  a global bigserial cannot (v0.6 §15.1).
* **Everything run-scoped cascades**, including `run_secrets`: when a run is deleted its
  encrypted provider keys go with it.
* **No prompt, skill or eval tables.** Those versions live in Langfuse; the run records the
  resolved `name@version` in `runs.prompt_versions` (v0.6 §6, §20.2).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from research_agent.contracts import RunStatus

# Predictable constraint names so autogenerated migrations stay reviewable.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}

_RUN_STATUS_VALUES = ", ".join(f"'{status.value}'" for status in RunStatus)

# Provider keys and per-run money amounts: six decimals is enough for per-token pricing and
# avoids the float rounding that would make the UI total disagree with the sum of the rows.
_MONEY = Numeric(14, 6)


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def _uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


def _created_at() -> Mapped[datetime]:
    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


class Run(Base):
    """One research question, from enqueue to report."""

    __tablename__ = "runs"

    id: Mapped[uuid.UUID] = _uuid_pk()
    # Not indexed on its own: every query that filters on status also orders by a timestamp,
    # and `ix_runs_status_created_at` below serves both.
    status: Mapped[str] = mapped_column(String(32), nullable=False, default=RunStatus.QUEUED.value)

    # The question is stored masked: raw PII never reaches the database (v0.6 §12, boundary B1).
    question_masked: Mapped[str] = mapped_column(Text, nullable=False)
    question_language: Mapped[str | None] = mapped_column(String(8))

    # Reproducibility: the effective config, its hash, and what was actually used (v0.6 §3).
    config_snapshot: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    config_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    overrides: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    prompt_versions: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    models_used: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    skills_used: Mapped[list[Any]] = mapped_column(JSONB, nullable=False, default=list)
    # Which provider keys came from the UI and which from the environment - never their values.
    key_sources: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)

    # Outcome.
    stop_reason: Mapped[str | None] = mapped_column(String(32))
    gate_status: Mapped[str | None] = mapped_column(String(32))
    error_code: Mapped[str | None] = mapped_column(String(64))
    error_message: Mapped[str | None] = mapped_column(Text)

    # Live counters. These always run, even when the wall-clock and cost gates are off (D11).
    iteration: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    searches_used: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    tokens_in: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    tokens_out: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost_usd: Mapped[float] = mapped_column(_MONEY, nullable=False, default=0)
    event_seq: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Scheduling, owned by the dispatcher.
    agent_id: Mapped[str | None] = mapped_column(String(128))
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cancel_requested: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    langfuse_trace_url: Mapped[str | None] = mapped_column(Text)

    created_at: Mapped[datetime] = _created_at()
    dispatched_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    heartbeat_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    deadline_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        CheckConstraint(f"status IN ({_RUN_STATUS_VALUES})", name="status"),
        CheckConstraint("attempts >= 0", name="attempts_non_negative"),
        # The dispatcher's claim query: oldest queued run first.
        Index("ix_runs_status_created_at", "status", "created_at"),
        # The watchdog's scan: runs that owe a heartbeat.
        Index("ix_runs_heartbeat_at", "heartbeat_at"),
    )


class RunSecret(Base):
    """Provider keys for one run, Fernet-encrypted, deleted when the run reaches a terminal state.

    The dispatcher never selects from this table (v0.6 §15.3): the control plane stays secret-free.
    """

    __tablename__ = "run_secrets"

    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), primary_key=True
    )
    provider: Mapped[str] = mapped_column(String(32), primary_key=True)
    ciphertext: Mapped[str] = mapped_column(Text, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = _created_at()


class RunEvent(Base):
    """Append-only timeline: the UI, the exported trace and the audit trail all read this.

    Both the agent and the dispatcher write here, so control-plane and agent decisions appear on
    a single timeline (v0.6 §14).
    """

    __tablename__ = "run_events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False
    )
    seq: Mapped[int] = mapped_column(Integer, nullable=False)
    ts: Mapped[datetime] = _created_at()

    level: Mapped[str] = mapped_column(String(16), nullable=False, default="info")
    node: Mapped[str] = mapped_column(String(64), nullable=False)
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    data: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)

    iteration: Mapped[int | None] = mapped_column(Integer)
    span_id: Mapped[str | None] = mapped_column(String(32))
    parent_span_id: Mapped[str | None] = mapped_column(String(32))
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    tokens_in: Mapped[int | None] = mapped_column(Integer)
    tokens_out: Mapped[int | None] = mapped_column(Integer)
    cost_usd: Mapped[float | None] = mapped_column(_MONEY)

    # Present only on failures; `expected=False` is the bug signal (v0.6 §13).
    error_code: Mapped[str | None] = mapped_column(String(64))
    expected: Mapped[bool | None] = mapped_column(Boolean)

    __table_args__ = (
        UniqueConstraint("run_id", "seq", name="uq_run_events_run_id_seq"),
        CheckConstraint("seq > 0", name="seq_positive"),
        Index("ix_run_events_run_id_seq", "run_id", "seq"),
    )


class LlmCall(Base):
    """One LLM request: cost, latency, the prompt version behind it, and redacted payloads."""

    __tablename__ = "llm_calls"

    id: Mapped[uuid.UUID] = _uuid_pk()
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False, index=True
    )
    span_id: Mapped[str] = mapped_column(String(32), nullable=False)
    node: Mapped[str] = mapped_column(String(64), nullable=False)
    iteration: Mapped[int | None] = mapped_column(Integer)

    provider: Mapped[str] = mapped_column(String(32), nullable=False)
    model: Mapped[str] = mapped_column(String(128), nullable=False)
    tier: Mapped[str] = mapped_column(String(16), nullable=False)
    prompt_id: Mapped[str | None] = mapped_column(String(64))
    prompt_version: Mapped[str | None] = mapped_column(String(32))

    tokens_in: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    tokens_out: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost_usd: Mapped[float] = mapped_column(_MONEY, nullable=False, default=0)
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    attempt: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    # Set when this call only happened because an earlier provider failed (`LLM_FALLBACK_USED`).
    fallback_from: Mapped[str | None] = mapped_column(String(32))
    status: Mapped[str] = mapped_column(String(16), nullable=False)
    error_code: Mapped[str | None] = mapped_column(String(64))

    request_redacted: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    response_redacted: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = _created_at()


class SearchCall(Base):
    """One search request, including the ones served from cache (cost-free but still recorded)."""

    __tablename__ = "search_calls"

    id: Mapped[uuid.UUID] = _uuid_pk()
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False, index=True
    )
    span_id: Mapped[str] = mapped_column(String(32), nullable=False)
    node: Mapped[str] = mapped_column(String(64), nullable=False)
    iteration: Mapped[int | None] = mapped_column(Integer)

    provider: Mapped[str] = mapped_column(String(32), nullable=False)
    query: Mapped[str] = mapped_column(Text, nullable=False)
    subquestion_id: Mapped[str | None] = mapped_column(String(32))

    status: Mapped[str] = mapped_column(String(16), nullable=False)
    result_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cache_hit: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    error_code: Mapped[str | None] = mapped_column(String(64))
    created_at: Mapped[datetime] = _created_at()


class RunArtifact(Base):
    """`state.json`, `report.md`, `report.json`, `gate_result.json`, `trace.jsonl`."""

    __tablename__ = "run_artifacts"

    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), primary_key=True
    )
    kind: Mapped[str] = mapped_column(String(32), primary_key=True)
    content_type: Mapped[str] = mapped_column(String(64), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    size_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = _created_at()


class SearchCache(Base):
    """Provider responses keyed by `sha256(provider + normalised query + params)`.

    This is what makes re-runs and the test suite cost nothing (v0.6 §16).
    """

    __tablename__ = "search_cache"

    key_hash: Mapped[str] = mapped_column(String(64), primary_key=True)
    provider: Mapped[str] = mapped_column(String(32), nullable=False)
    query: Mapped[str] = mapped_column(Text, nullable=False)
    response: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = _created_at()
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )


class EmbeddingCache(Base):
    """Claim embeddings keyed by `sha256(model + text)` (D6).

    Vectors are stored as a JSON array rather than pgvector: clustering happens in-process on a
    few hundred claims, so an index would buy nothing and pgvector would add an extension to the
    reviewer's setup. The production note is in v0.6 §19.
    """

    __tablename__ = "embedding_cache"

    key_hash: Mapped[str] = mapped_column(String(64), primary_key=True)
    model: Mapped[str] = mapped_column(String(128), nullable=False)
    dimensions: Mapped[int] = mapped_column(Integer, nullable=False)
    vector: Mapped[list[float]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = _created_at()


class Preset(Base):
    """A named set of per-run overrides, saved from the UI. Never written back to YAML (D24)."""

    __tablename__ = "presets"

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    description: Mapped[str | None] = mapped_column(Text)
    overrides: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = _created_at()
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
